#feature-id AstroProcessing > ReproduciblePipeline
#feature-info Constrained post-integration OSC workflow; generated by astro-processing.

var ASTRO_PARAMS_PATH = __ASTRO_PARAMS_JSON__;

function loadParams()
{
   return JSON.parse( File.readTextFile( ASTRO_PARAMS_PATH ) );
}

function writeJson( path, value )
{
   File.writeTextFile( path, JSON.stringify( value, null, 2 ) + "\n" );
}

function stats( image )
{
   var median = [], avgDev = [], minimum = [], maximum = [];
   for ( var c = 0; c < image.numberOfChannels; ++c )
   {
      image.selectedChannel = c;
      median.push( image.median() );
      avgDev.push( image.avgDev() );
      minimum.push( image.minimum() );
      maximum.push( image.maximum() );
   }
   image.resetSelections();
   return { median:median, avgDev:avgDev, minimum:minimum, maximum:maximum };
}

function signature( image )
{
   var xy = [[0,0],[image.width-1,0],[0,image.height-1],[image.width-1,image.height-1],
             [Math.floor(image.width/2),Math.floor(image.height/2)]];
   var result = [];
   for ( var i = 0; i < xy.length; ++i )
   {
      var p = [];
      for ( var c = 0; c < image.numberOfChannels; ++c )
         p.push( image.sample( xy[i][0], xy[i][1], c ) );
      result.push( p );
   }
   return result;
}

function inspectWindow( w, declaredLinear )
{
   var image = w.mainView.image;
   return {
      width:image.width, height:image.height, channels:image.numberOfChannels,
      bitsPerSample:image.bitsPerSample, isReal:image.isReal, isColor:image.isColor,
      linear:declaredLinear, hasWCS:w.hasAstrometricSolution,
      orientationSignature:signature( image ), statistics:stats( image )
   };
}

function sameSignature( a, b, tolerance )
{
   if ( a.length != b.length ) return false;
   for ( var i = 0; i < a.length; ++i )
      for ( var c = 0; c < a[i].length; ++c )
         if ( Math.abs( a[i][c] - b[i][c] ) > tolerance ) return false;
   return true;
}

function verifyReopen( path, expected, declaredLinear, exactOrientation, expectedBits, expectedReal, requireWCSPreservation )
{
   var windows = ImageWindow.open( path );
   if ( windows.length < 1 ) throw new Error( "Unable to reopen " + path );
   var w = windows[0], actual = inspectWindow( w, declaredLinear );
   actual.path = path;
   actual.sameDimensions = actual.width == expected.width && actual.height == expected.height;
   actual.sameChannels = actual.channels == expected.channels;
   actual.expectedBitsPerSample = expectedBits;
   actual.expectedReal = expectedReal;
   actual.bitDepthOK = actual.bitsPerSample == expectedBits && actual.isReal == expectedReal;
   actual.wcsChecked = true;
   actual.wcsPreserved = actual.hasWCS == expected.hasWCS;
   actual.orientationOK = !exactOrientation || sameSignature( expected.orientationSignature, actual.orientationSignature, 2.0e-6 );
   w.forceClose();
   if ( !actual.sameDimensions || !actual.sameChannels || !actual.bitDepthOK ||
        (requireWCSPreservation && !actual.wcsPreserved) || !actual.orientationOK )
      throw new Error( "Boundary validation failed for " + path );
   return actual;
}

function saveAndVerify( w, path, declaredLinear, expectedBits, expectedReal, exactOrientation, requireWCSPreservation )
{
   var expected = inspectWindow( w, declaredLinear );
   if ( !w.saveAs( path, false, false, false, false ) )
      throw new Error( "Unable to save " + path );
   return verifyReopen( path, expected, declaredLinear, exactOrientation, expectedBits, expectedReal, requireWCSPreservation );
}

function copyMetadata( source, destination )
{
   destination.mainView.beginProcess();
   destination.keywords = source.keywords;
   destination.metadataWCS = source.metadataWCS;
   var properties = source.mainView.properties;
   for ( var i = 0; i < properties.length; ++i )
   {
      try { destination.mainView.setPropertyValue( properties[i], source.mainView.propertyValue( properties[i] ) ); }
      catch ( e ) { console.warningln( "Unable to copy property ", properties[i], ": ", e.toString() ); }
   }
   destination.regenerateAstrometricSolution();
   destination.mainView.endProcess();
}

function stretch( w, midtones )
{
   var H = new HistogramTransformation;
   H.H = [[0,0.5,1,0,1],[0,0.5,1,0,1],[0,0.5,1,0,1],[0,midtones,1,0,1],[0,0.5,1,0,1]];
   if ( !H.executeOn( w.mainView, false ) ) throw new Error( "HistogramTransformation failed" );
}

function saturate( w, amount )
{
   var C = new ColorSaturation;
   C.HS = [[0,amount],[1,amount]];
   C.HSt = C.AkimaSubsplines;
   C.hueShift = 0;
   if ( !C.executeOn( w.mainView, false ) ) throw new Error( "ColorSaturation failed" );
}

function runABE( source, cfg, outputPath, modelPath )
{
   var beforeIds = {}, oldWindows = ImageWindow.windows;
   for ( var i = 0; i < oldWindows.length; ++i ) beforeIds[oldWindows[i].mainView.id] = true;
   var correctedId = "astro_abe_" + Math.round( 1000000*Math.random() );
   var A = new AutomaticBackgroundExtractor;
   A.tolerance = cfg.tolerance; A.deviation = cfg.deviation; A.unbalance = 1.8;
   A.polyDegree = cfg.degree; A.boxSize = cfg.box_size; A.boxSeparation = cfg.box_separation;
   A.modelImageSampleFormat = AutomaticBackgroundExtractor.prototype.f32;
   A.abeDownsample = cfg.downsample; A.targetCorrection = AutomaticBackgroundExtractor.prototype.Subtract;
   A.normalize = false; A.discardModel = false; A.replaceTarget = false;
   A.correctedImageId = correctedId; A.correctedImageSampleFormat = AutomaticBackgroundExtractor.prototype.SameAsTarget;
   if ( !A.executeOn( source.mainView, false ) ) throw new Error( "ABE returned false" );
   var corrected = ImageWindow.windowById( correctedId );
   if ( corrected.isNull ) throw new Error( "ABE corrected window not found" );
   var model = null, all = ImageWindow.windows;
   for ( var j = 0; j < all.length; ++j )
      if ( !beforeIds[all[j].mainView.id] && all[j].mainView.id != correctedId ) { model = all[j]; break; }
   if ( model == null ) throw new Error( "ABE model window not found" );
   copyMetadata( source, corrected );
   var correctedInfo = saveAndVerify( corrected, outputPath, true, 32, true, true, true );
   var modelInfo = saveAndVerify( model, modelPath, true, 32, true, true, false );
   model.forceClose(); source.forceClose();
   return { window:corrected, evidence:{process:"AutomaticBackgroundExtractor",parameters:cfg,corrected:correctedInfo,model:modelInfo} };
}

function runClassicColor( w, cfg, bnPath, outputPath )
{
   var before = inspectWindow( w, true );
   var BN = new BackgroundNeutralization;
   BN.backgroundReferenceViewId = ""; BN.backgroundLow = cfg.background_low; BN.backgroundHigh = cfg.background_high;
   BN.useROI = false; BN.mode = BN.RescaleAsNeeded; BN.targetBackground = cfg.target_background;
   if ( !BN.executeOn( w.mainView, false ) ) throw new Error( "BackgroundNeutralization returned false" );
   var bn = saveAndVerify( w, bnPath, true, 32, true, true, true );
   var CC = new ColorCalibration;
   CC.whiteReferenceViewId = ""; CC.whiteLow = cfg.white_low; CC.whiteHigh = cfg.white_high;
   CC.whiteUseROI = false; CC.structureDetection = true; CC.structureLayers = cfg.structure_layers;
   CC.noiseLayers = cfg.noise_layers; CC.manualWhiteBalance = false;
   CC.backgroundReferenceViewId = ""; CC.backgroundLow = cfg.background_low; CC.backgroundHigh = cfg.background_high;
   CC.backgroundUseROI = false; CC.outputWhiteReferenceMask = false; CC.outputBackgroundReferenceMask = false;
   if ( !CC.executeOn( w.mainView, false ) ) throw new Error( "ColorCalibration returned false" );
   var output = saveAndVerify( w, outputPath, true, 32, true, true, true );
   return { process:"BackgroundNeutralization + classic ColorCalibration", photometric:false, degradation:"SPCC skipped", parameters:cfg, before:before, backgroundNeutralized:bn, output:output };
}

function runBXT( w, cfg, outputPath )
{
   var before = inspectWindow( w, true ), P = new BlurXTerminator;
   P.ai_file = cfg.model; P.correct_only = false; P.correct_first = cfg.correct_first;
   P.nonstellar_then_stellar = false; P.lum_only = false; P.sharpen_stars = cfg.sharpen_stars;
   P.adjust_halos = cfg.adjust_halos; P.auto_nonstellar_psf = true; P.sharpen_nonstellar = cfg.sharpen_nonstellar;
   if ( !P.executeOn( w.mainView, false ) ) throw new Error( "BlurXTerminator returned false" );
   return { process:"BlurXTerminator", model:cfg.model, parameters:cfg, before:before, output:saveAndVerify(w,outputPath,true,32,true,true,true) };
}

function runSXT( w, cfg, starlessPath, starsPath )
{
   var known = {}, old = ImageWindow.windows;
   for ( var i = 0; i < old.length; ++i ) known[old[i].mainView.id] = true;
   var P = new StarXTerminator;
   P.ai_file = cfg.model; P.stars = true; P.unscreen = cfg.unscreen; P.overlap = cfg.overlap;
   if ( !P.executeOn( w.mainView, false ) ) throw new Error( "StarXTerminator returned false" );
   var stars = null, all = ImageWindow.windows;
   for ( var j = 0; j < all.length; ++j ) if ( !known[all[j].mainView.id] ) { stars = all[j]; break; }
   if ( stars == null ) throw new Error( "StarXTerminator star layer not found" );
   return { starless:w, stars:stars, evidence:{process:"StarXTerminator",model:cfg.model,parameters:cfg,
      starless:saveAndVerify(w,starlessPath,true,32,true,true,true),stars:saveAndVerify(stars,starsPath,true,32,true,true,false)} };
}

function runNXT( w, cfg, outputPath )
{
   var before = inspectWindow( w, true ), P = new NoiseXTerminator;
   P.ai_file = cfg.model; P.enable_color_separation = true; P.enable_frequency_separation = false;
   P.denoise = cfg.denoise; P.denoise_color = cfg.denoise_color; P.iterations = cfg.iterations; P.detail = cfg.detail;
   if ( !P.executeOn( w.mainView, false ) ) throw new Error( "NoiseXTerminator returned false" );
   return { process:"NoiseXTerminator",appliedTo:"starless linear layer only",model:cfg.model,parameters:cfg,before:before,
      output:saveAndVerify(w,outputPath,true,32,true,true,true) };
}

function runMLT( w, outputPath )
{
   var before = inspectWindow( w, true ), M = new MultiscaleLinearTransform;
   M.layers = [[true,true,0,true,3,.70,1],[true,true,0,true,2.5,.50,1],[true,true,0,true,2,.30,1],
               [true,true,0,false,3,1,1],[true,true,0,false,3,1,1]];
   M.transform=M.StarletTransform; M.scaleDelta=0;
   M.scalingFunctionData=[.25,.5,.25,.5,1,.5,.25,.5,.25]; M.scalingFunctionRowFilter=[.5,1,.5]; M.scalingFunctionColFilter=[.5,1,.5];
   M.scalingFunctionNoiseSigma=[.8003,.2729,.1198,.0578,.0287,.0143,.0072,.0036,.0019,.0010];
   M.scalingFunctionName="Linear Interpolation (3)"; M.linearMask=true; M.linearMaskAmpFactor=5; M.linearMaskSmoothness=1;
   M.linearMaskInverted=true; M.noiseThresholding=false; M.softThresholding=true; M.useMultiresolutionSupport=false;
   M.deringing=false; M.toLuminance=true; M.toChrominance=true; M.linear=true;
   if ( !M.executeOn( w.mainView, false ) ) throw new Error( "MLT returned false" );
   return { process:"MultiscaleLinearTransform",parameters:{linearMask:true,linearMaskAmpFactor:5,softThresholding:true},before:before,
      output:saveAndVerify(w,outputPath,true,32,true,true,true) };
}

function exportFinal( w, output, prefix, declaredLinear )
{
   var expected = inspectWindow( w, declaredLinear ), evidence = [];
   evidence.push( saveAndVerify( w, output.exports + "/" + prefix + ".xisf", declaredLinear, 32, true, true, true ) );
   evidence.push( saveAndVerify( w, output.exports + "/" + prefix + ".fits", declaredLinear, 32, true, true, true ) );
   evidence.push( saveAndVerify( w, output.exports + "/" + prefix + ".tif", declaredLinear, 32, true, true, false ) );
   evidence.push( saveAndVerify( w, output.exports + "/" + prefix + ".png", declaredLinear, 8, false, false, false ) );
   evidence.push( saveAndVerify( w, output.exports + "/" + prefix + ".jpg", declaredLinear, 8, false, false, false ) );
   return { expected:expected, files:evidence, fitsBoundary:{format:"FITS",bitsPerSample:32,isReal:true,
      checks:["dimensions","channels","bit depth","declared linear state","WCS","corner/center orientation signature"]} };
}

function syntheticWindow()
{
   var w = new ImageWindow( 96, 64, 3, 32, true, true, "astro_smoke" );
   w.mainView.beginProcess();
   var image = w.mainView.image;
   for ( var c = 0; c < 3; ++c )
      for ( var y = 0; y < image.height; ++y )
         for ( var x = 0; x < image.width; ++x )
            image.setSample( (x + 2*y + 11*c)/(96 + 2*64 + 22), x, y, c );
   w.mainView.endProcess();
   return w;
}

function runSmoke( params, result )
{
   var w = syntheticWindow();
   var source = saveAndVerify( w, params.output.checkpoints + "/synthetic-linear.xisf", true, 32, true, true, true );
   result.input = source;
   result.exports = exportFinal( w, params.output, "synthetic-smoke", true );
   result.stages.push( {stage:"synthetic-create",ok:true} );
   result.stages.push( {stage:"export-and-reopen",ok:true} );
   w.forceClose();
}

function runPipeline( params, result )
{
   var windows = ImageWindow.open( params.input );
   if ( windows.length < 1 ) throw new Error( "Unable to open input XISF" );
   var w = windows[0], inputInfo = inspectWindow( w, true );
   if ( inputInfo.channels != 3 || !inputInfo.isColor || inputInfo.bitsPerSample != 32 || !inputInfo.isReal )
      throw new Error( "Expected OSC RGB Float32 integrated-linear XISF" );
   result.input = inputInfo;
   var b = runABE( w, params.stages.background, params.output.checkpoints+"/01-abe-linear.xisf", params.output.checkpoints+"/01-abe-model.xisf" );
   w = b.window; result.stages.push( {stage:"background-extraction",ok:true,evidence:b.evidence} );
   var color = runClassicColor( w, params.stages.color, params.output.checkpoints+"/02-bn-linear.xisf", params.output.checkpoints+"/02-color-linear.xisf" );
   result.stages.push( {stage:"color-calibration",ok:true,evidence:color} );
   var rc = params.stages.rc_astro;
   if ( rc.enabled )
   {
      if ( !rc.license_confirmed ) throw new Error( "RC-Astro license confirmation is required" );
      result.stages.push( {stage:"deconvolution",ok:true,evidence:runBXT(w,rc.bxt,params.output.checkpoints+"/03-bxt-linear.xisf")} );
      var separated = runSXT( w, rc.sxt, params.output.checkpoints+"/04-starless-linear.xisf", params.output.checkpoints+"/04-stars-linear.xisf" );
      w = separated.starless; var stars = separated.stars;
      result.stages.push( {stage:"star-separation",ok:true,evidence:separated.evidence} );
      result.stages.push( {stage:"denoise",ok:true,evidence:runNXT(w,rc.nxt,params.output.checkpoints+"/05-nxt-starless-linear.xisf")} );
      stretch( w, params.stages.finish.starless_midtones ); saturate( w, params.stages.finish.starless_saturation );
      stretch( stars, params.stages.finish.stars_midtones ); saturate( stars, params.stages.finish.stars_saturation );
      var P = new PixelMath;
      P.expression = "1-(1-"+w.mainView.id+")*(1-"+params.stages.finish.star_strength+"*"+stars.mainView.id+")";
      P.useSingleExpression=true; P.symbols=""; P.generateOutput=true; P.singleThreaded=false; P.optimization=true;
      P.rescale=false; P.truncate=true; P.truncateLower=0; P.truncateUpper=1; P.createNewImage=true; P.showNewImage=true;
      P.newImageId="astro_final_rc"; P.newImageWidth=0; P.newImageHeight=0; P.newImageAlpha=false;
      P.newImageColorSpace=PixelMath.prototype.SameAsTarget; P.newImageSampleFormat=PixelMath.prototype.f32;
      if ( !P.executeOn( w.mainView, false ) ) throw new Error( "Screen reconstruction failed" );
      var finalWindow = ImageWindow.windowById( "astro_final_rc" );
      if ( finalWindow.isNull ) throw new Error( "Final reconstruction window missing" );
      copyMetadata( w, finalWindow );
      result.stages.push( {stage:"stretch-and-star-reconstruction",ok:true,parameters:params.stages.finish} );
      result.exports = exportFinal( finalWindow, params.output, "final-rc-balanced", false );
      finalWindow.forceClose(); stars.forceClose(); w.forceClose();
   }
   else
   {
      result.stages.push( {stage:"denoise",ok:true,evidence:runMLT(w,params.output.checkpoints+"/03-mlt-linear.xisf")} );
      stretch( w, params.stages.finish.single_midtones ); saturate( w, params.stages.finish.single_saturation );
      result.stages.push( {stage:"stretch",ok:true,parameters:{midtones:params.stages.finish.single_midtones,saturation:params.stages.finish.single_saturation}} );
      result.exports = exportFinal( w, params.output, "final-balanced", false );
      w.forceClose();
   }
}

var params = loadParams();
var result = {schema_version:1,ok:false,execution_id:params.execution_id || null,mode:params.mode,stages:[],
   pixinsight:{versionMajor:CoreApplication.versionMajor,versionMinor:CoreApplication.versionMinor,
      versionRelease:CoreApplication.versionRelease,versionRevision:CoreApplication.versionRevision,
      versionBuild:CoreApplication.versionBuild},
   execution:{mechanism:"--execute IPC to running GUI",headless:false,params:ASTRO_PARAMS_PATH},
   limitations:params.limitations};
try
{
   console.beginLog( params.console_log );
   if ( params.mode == "smoke" ) runSmoke( params, result ); else runPipeline( params, result );
   result.ok = true; result.successMarker = "ASTRO_PROCESSING_PIXINSIGHT_OK";
   writeJson( params.result, result );
   console.noteln( result.successMarker );
   console.endLog();
}
catch ( e )
{
   result.error = e.toString(); result.message = e.message ? e.message : ""; result.stack = e.stack ? e.stack : "";
   writeJson( params.result, result );
   try { console.endLog(); } catch ( logError ) {}
   throw e;
}
